version: "2.0"
services:
  js-server:
    build:
      context: js-server/.
  ng-squares:
    build:
      context: ng-squares/.
    ports:
      - "8000:80"
    volumes:
      - ./ng-squares/nginx/:/etc/nginx/conf.d/
